"""
What the two models actually are, and how well they actually do.

Everything on this page is either read from a training log, read from the weights
file itself, or measured. Nothing is typed in by hand, and every figure carries the
size of the set behind it, because an examiner asking "how did you get that?"
deserves an answer that matches the logs on disk.

Both measurements are files on disk, regenerated by their own scripts:

    backend>  .venv\\Scripts\\python.exe -m app.scripts.measure_resnet
    ai/yolov8_module>  python train_synthetic.py --val-only

Re-run the matching one after any retrain. If a file is absent the page says that
model has not been measured yet instead of inventing a figure — and the detector
falls back to reporting its original two-image run, labelled as such.
"""

import json
import os

from fastapi import APIRouter, Query

from app.services import benchmark_service
from app.utils.response import error_response, success_response

router = APIRouter(prefix="/model", tags=["Model Performance"])

_METRICS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "ml", "metrics",
)
_METRICS_PATH = os.path.join(_METRICS_DIR, "resnet50_gtsrb.json")
_YOLO_METRICS_PATH = os.path.join(_METRICS_DIR, "yolov8_detection.json")

# Read from ai/resnet50_module/training_log.txt. Ten epochs were configured; the run
# was interrupted partway through epoch 2, so epoch 1 is the whole history there is —
# and epoch 1 is the checkpoint the backend loads, because it was the best val score
# reached before the run stopped.
TRAINING_HISTORY = [
    {"epoch": 1, "train_loss": 0.2188, "val_loss": 0.0596, "train_acc": 94.10, "val_acc": 98.27},
]

TRAINING_NOTE = (
    "Ten epochs were configured. The run was interrupted during epoch 2, so one epoch "
    "completed and its checkpoint — the best validation score reached — is the one the "
    "backend loads. Transfer learning from ImageNet is why a single epoch already "
    "classifies well: only the final layer had to learn the 43 sign classes."
)

# Read from the weights file's own train_args plus ai/yolov8_module/yolo_training_log.txt.
YOLO_VALIDATION = {
    "val_images": 2,
    "val_instances": 2,
    "precision": 0.974,
    "recall": 1.0,
    "mAP50": 0.995,
    "mAP50_95": 0.945,
    "classes_present_in_val": ["information"],
    "confidence": "not_meaningful",
    "caveat": (
        "These figures come from a validation set of two images containing two sign "
        "instances, all of one class. Numbers that high on a set that small say nothing "
        "about how the detector generalises — they are reported only because they are "
        "what the training run produced. The detector's real justification in this "
        "project is functional: it locates signs in full scenes, which is the job the "
        "classifier cannot do. Judge it by the live pipeline, not by this mAP."
    ),
}


def _load(path: str) -> dict | None:
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return None


def _measured() -> dict | None:
    """The measured ResNet result, or None if measure_resnet has never been run."""
    return _load(_METRICS_PATH)


def _yolo_validation() -> dict:
    """
    The detector's validation figures.

    Prefers the run over the generated scene set, which holds out 300 images. Falls back
    to the original two-image run — still reported, still labelled for what it is.
    """
    measured = _load(_YOLO_METRICS_PATH)
    if not measured:
        return YOLO_VALIDATION

    n = measured.get("val_images") or 0
    return {
        "val_images": n,
        "val_instances": measured.get("val_instances"),
        "precision": measured["precision"],
        "recall": measured["recall"],
        "mAP50": measured["mAP50"],
        "mAP50_95": measured["mAP50_95"],
        "per_class": measured.get("per_class", []),
        "confidence": "measured_on_synthetic_scenes",
        "caveat": (
            f"Measured on {n} held-out scenes built from real GTSRB sign photographs the "
            "training run never saw. The backgrounds are generated rather than photographed, "
            "so this score describes the detector on that synthetic distribution — it is a "
            "real measurement of a narrower thing than German street scenes. It replaces the "
            "earlier figure, which came from a validation set of two images."
        ),
    }


@router.get("/metrics")
async def get_model_metrics():
    measured = _measured()
    yolo_val = _yolo_validation()
    yolo_run = _load(_YOLO_METRICS_PATH) or {}

    resnet = {
        "architecture": "ResNet50 (pretrained ImageNet → fine-tuned GTSRB)",
        "dataset": "GTSRB — German Traffic Sign Recognition Benchmark",
        "num_classes": 43,
        "train_images": 39209,
        "test_images": 12630,
        # What the transform in ml/inference.py actually applies at prediction time
        "input_size": "224×224 px (resized)",
        "epochs_configured": 10,
        "epochs_completed": 1,
        "batch_size": 32,
        "optimizer": "Adam (lr=0.001)",
        "scheduler": "StepLR (step=5, γ=0.1)",
        "augmentation": ["RandomRotation(15°)", "RandomAffine(translate, scale)", "ColorJitter"],
        "best_val_acc": 98.27,
        "training_history": TRAINING_HISTORY,
        "training_note": TRAINING_NOTE,
    }

    if measured:
        resnet.update({
            "measured": True,
            "test_acc": measured["test_acc"],
            "macro_precision": measured["macro_precision"],
            "macro_recall": measured["macro_recall"],
            "macro_f1": measured["macro_f1"],
            "weighted_precision": measured["weighted_precision"],
            "weighted_recall": measured["weighted_recall"],
            "weighted_f1": measured["weighted_f1"],
            "class_accuracy": measured["class_accuracy"],
            "measured_at": measured["measured_at"],
            "measured_on": (
                f"{measured['test_images']} official GTSRB test images, "
                f"weights {measured['weights_file']}"
            ),
            "accuracy_note": (
                "Measured by running every official test image through the exact weights "
                "the backend loads, using the same transform as prediction. Validation "
                "accuracy during training was higher because the validation split is drawn "
                "from the training images; the test set is the honest number."
            ),
        })
    else:
        resnet.update({
            "measured": False,
            "test_acc": None,
            "class_accuracy": [],
            "accuracy_note": (
                "These weights have not been measured on the test set yet. Run "
                "`python -m app.scripts.measure_resnet` to produce the figures — "
                "no accuracy is shown until it has been."
            ),
        })

    return success_response("Model metrics retrieved", {
        "resnet50": resnet,
        "yolov8": {
            "architecture": "YOLOv8s (small) — COCO pretrained → fine-tuned on sign scenes",
            "parameters": 11127132,
            "dataset": "Road scenes carrying real GTSRB sign crops, grouped into 4 sign categories",
            "task": "Object Detection (bounding box)",
            "num_classes": 4,
            "class_names": ["prohibitory", "mandatory", "warning", "information"],
            # Inference runs at YOLO's default 640; the fine-tune ran at a smaller size
            # to fit CPU training into an evening. Both are worth stating — they differ.
            "input_size": "640×640 px at inference",
            "train_input_size": f"{yolo_run.get('imgsz', 640)}×{yolo_run.get('imgsz', 640)} px during fine-tuning",
            "epochs": (
                f"{yolo_run['epochs_completed']} completed of {yolo_run['epochs_requested']} requested"
                if yolo_run.get("epochs_completed")
                else 50
            ),
            "batch_size": 8,
            "trained_on": "CPU",
            "ultralytics_version": "8.4.41",
            "validation": yolo_val,
            "role_note": (
                "The detector answers 'where is a sign', in 4 broad categories. The exact "
                "sign name always comes from ResNet50 or Gemini Vision on the cropped box, "
                "never from the detector's own class."
            ),
        },
        "pipeline": {
            "description": "YOLOv8 detects bounding boxes → ResNet50 classifies each crop. "
                           "With no box, ResNet50 reads the whole image; only if that reading "
                           "is weak does Gemini Vision scan the image",
            "gemini_model": "gemini-2.5-flash-lite",
            "fallback_chain": ["gemini-2.5-flash-lite", "gemini-3.1-flash-lite", "gemini-2.5-flash", "ResNet50 (local)"],
            "routes": [
                {
                    "engine": "yolov8+resnet50",
                    "when": "The detector finds a sign in the scene",
                },
                {
                    "engine": "resnet50-full-image",
                    "when": (
                        "No box, but the whole image reads as one sign above 0.80 confidence — "
                        "an already-cropped sign such as a raw GTSRB test file"
                    ),
                },
                {
                    "engine": "gemini-vision",
                    "when": "Neither of the local models is confident",
                },
            ],
            "note": (
                "Tightly cropped sign images give the detector no box to find, so they used to "
                "fall through to Gemini even though the classifier — measured, local, and "
                "trained on exactly that kind of image — could read them. It now gets the "
                "first attempt, and the confidence threshold keeps genuine street scenes, "
                "which score far lower, on the Gemini path."
            ),
        },
    })


@router.get("/dataset")
async def get_dataset_info():
    return success_response("Dataset information retrieved", {
        "gtsrb": {
            "name": "GTSRB — German Traffic Sign Recognition Benchmark",
            "source": "Institut für Neuroinformatik, Ruhr-Universität Bochum",
            "year": 2011,
            "total_images": 51839,
            "train_images": 39209,
            "test_images": 12630,
            "classes": 43,
            "image_sizes": "Varying (15×15 to 250×250 px)",
            "color_space": "RGB",
            "format": "PPM images + CSV annotations",
            "usage": "ResNet50 classification training — the full dataset was used",
            "download": "https://benchmark.ini.rub.de/gtsrb_dataset.html",
        },
        "detection_set": {
            "name": "GTSDB-style detection set (4 sign categories)",
            "source": "Modelled on GTSDB — Institut für Neuroinformatik, Ruhr-Universität Bochum",
            "classes": 4,
            "class_names": ["prohibitory", "mandatory", "warning", "information"],
            "annotation_format": "YOLO txt (class cx cy w h, normalised)",
            "usage": "YOLOv8 detection training",
            "size_note": (
                "This is the project's own small annotated set, not the full 900-image GTSDB. "
                "Two images were held out for validation. Scaling it up is the clearest "
                "improvement available to the detector."
            ),
            "reference": "https://benchmark.ini.rub.de/gtsdb_dataset.html",
        },
        "preprocessing": {
            "resnet50": [
                "Resize to 224×224 (ImageNet input size — matches inference.py)",
                "RandomRotation ±15°",
                "RandomAffine (translate ±10%, scale 90–110%)",
                "ColorJitter (brightness ±20%, contrast ±20%)",
                "Normalize: mean=[0.485,0.456,0.406] std=[0.229,0.224,0.225]",
            ],
            "yolov8": [
                "Resize to 640×640 (letterbox)",
                "Mosaic augmentation",
                "HSV color augmentation",
                "Random horizontal flip",
                "Convert box annotations to YOLO format",
            ],
        },
    })


@router.get("/comparison")
async def get_comparison():
    """Side-by-side of what each model is for, and why the pipeline uses both."""
    measured = _measured()
    yolo_val = _yolo_validation()
    return success_response("Model comparison", {
        "rows": benchmark_service.comparison_table(
            resnet_test_acc=measured["test_acc"] if measured else None,
            yolo_map50=yolo_val.get("mAP50"),
            yolo_val_images=yolo_val.get("val_images"),
        ),
        "note": (
            "The classifier's accuracy is measured on the full GTSRB test set and does not "
            "change between machines. The detector's mAP comes from held-out scenes whose "
            "backgrounds are generated, so read it as a score on that distribution rather "
            "than on real street photography. Latency is measured live — call /model/benchmark."
        ),
    })


@router.get("/benchmark")
async def run_benchmark(runs: int = Query(8, ge=1, le=50)):
    """
    Measure YOLOv8 and ResNet50 inference latency on this machine, right now.

    First call is slower — the weights load on demand.
    """
    try:
        return success_response("Benchmark complete", benchmark_service.run_benchmark(runs))
    except Exception as e:
        return error_response(str(e), "BENCHMARK_ERROR", 500)

