"""
Driver report as a PDF.

Pulls together everything the app knows about one driver — outstanding fines and what
they cost today, the demerit balance, documents and their expiry, and recent AI
detections — into a single document they can print or send on.

Built with ReportLab's platypus flowables so the layout reflows across pages by itself
rather than being positioned by hand.
"""

from datetime import date, datetime
from io import BytesIO

from sqlalchemy.orm import Session

from app.models.prediction import Prediction
from app.services.demerit_service import DemeritService
from app.services.locker_service import LockerService
from app.services.spot_fine_service import SpotFineService

# Matches the app's palette so the PDF looks like it came from the same product
SIGNAL = "#f5a623"
ALERT = "#e03131"
GO = "#1faa59"
INK = "#0b1220"
MUTED = "#64748b"


def _styles():
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.colors import HexColor

    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=base["Title"], fontSize=20, spaceAfter=4,
                                textColor=HexColor(INK), alignment=TA_LEFT),
        "subtitle": ParagraphStyle("st", parent=base["Normal"], fontSize=9,
                                   textColor=HexColor(MUTED), spaceAfter=16),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontSize=13,
                             textColor=HexColor(INK), spaceBefore=16, spaceAfter=6),
        "body": ParagraphStyle("b", parent=base["Normal"], fontSize=9,
                               textColor=HexColor(INK), leading=13),
        "muted": ParagraphStyle("m", parent=base["Normal"], fontSize=8,
                                textColor=HexColor(MUTED), leading=11),
        "empty": ParagraphStyle("e", parent=base["Normal"], fontSize=9,
                                textColor=HexColor(MUTED), leftIndent=4, spaceAfter=4),
    }


def _table(data, widths, highlight_col: int | None = None, highlight_rows=None):
    from reportlab.lib import colors
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import Table, TableStyle

    table = Table(data, colWidths=widths, repeatRows=1, hAlign="LEFT")
    style = [
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("BACKGROUND", (0, 0), (-1, 0), HexColor(INK)),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.4, HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, HexColor("#f8fafc")]),
    ]
    for row in highlight_rows or []:
        style.append(("TEXTCOLOR", (highlight_col or 0, row), (-1, row), HexColor(ALERT)))
        style.append(("FONTNAME", (0, row), (-1, row), "Helvetica-Bold"))
    table.setStyle(TableStyle(style))
    return table


def _page_furniture(canvas, doc):
    """Rule at the top, page number and disclaimer at the foot, on every page."""
    from reportlab.lib.colors import HexColor

    canvas.saveState()
    width, height = doc.pagesize

    canvas.setStrokeColor(HexColor(SIGNAL))
    canvas.setLineWidth(3)
    canvas.line(40, height - 40, width - 40, height - 40)

    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(HexColor(MUTED))
    canvas.drawString(40, 28, "Generated by RoadSafety AI — informational only, no legal standing.")
    canvas.drawRightString(width - 40, 28, f"Page {doc.page}")
    canvas.restoreState()


def build_driver_report(fines: list[dict], summary: dict, balance: dict,
                        demerit_records: list[dict], documents: list[dict],
                        detections: list[dict], driver_name: str | None = None,
                        today: date | None = None) -> bytes:
    """
    Everything the driver holds, as a PDF.

    Takes already-derived data rather than a database session: the records live in the
    driver's browser, so they arrive in the request and nothing is read or written here.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph, Spacer

    today = today or date.today()
    s = _styles()
    buffer = BytesIO()

    doc = BaseDocTemplate(
        buffer, pagesize=A4,
        leftMargin=40, rightMargin=40, topMargin=60, bottomMargin=45,
        title="Driver Report", author="RoadSafety AI",
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="body")
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_page_furniture)])

    story = [
        Paragraph("Driver Report", s["title"]),
        Paragraph(
            f"{driver_name or 'Driver'} &nbsp;·&nbsp; generated "
            f"{datetime.now().strftime('%d %B %Y at %H:%M')}",
            s["subtitle"],
        ),
    ]

    # ── Outstanding fines ───────────────────────────────────────────────────────
    pending = [f for f in fines if f.get("status") != "paid"]

    story.append(Paragraph("Outstanding fines", s["h2"]))
    if not pending:
        story.append(Paragraph("No outstanding fines.", s["empty"]))
    else:
        rows = [["Offence", "Issued", "Stage", "Payable now", "Days left"]]
        overdue_rows = []
        for i, f in enumerate(pending, start=1):
            c = f["countdown"]
            if c["stage"] in ("double", "court"):
                overdue_rows.append(i)
            rows.append([
                Paragraph(f["offence"], s["body"]),
                f["issued_date"],
                c["stage"].title(),
                f"{c['payable_now_lkr']:,.0f}" if c["payable_now_lkr"] is not None else "Court",
                str(c["days_left"]) if c["days_left"] is not None else "—",
            ])
        story.append(_table(rows, [165, 60, 55, 75, 50], highlight_rows=overdue_rows))
        story.append(Spacer(1, 6))
        story.append(Paragraph(
            f"<b>{summary['pending']}</b> pending &nbsp;·&nbsp; "
            f"<b>LKR {summary['total_payable_now_lkr']:,.0f}</b> payable today &nbsp;·&nbsp; "
            f"next deadline {summary['next_deadline'] or '—'}",
            s["body"],
        ))

    # ── Demerit points ──────────────────────────────────────────────────────────
    records = demerit_records

    story.append(Paragraph("Demerit points", s["h2"]))
    story.append(Paragraph(
        f"<b>{balance['total_points']} of {balance['threshold']}</b> points "
        f"in the last {balance['window_months']} months — {balance['tier_label']}. "
        f"{balance['advice']}",
        s["body"],
    ))
    active = [r for r in records if r["active"]]
    if active:
        story.append(Spacer(1, 6))
        rows = [["Offence", "Date", "Points", "Drops off"]]
        for r in active:
            rows.append([
                Paragraph(r["offence"], s["body"]),
                r["offence_date"],
                str(r["points"]),
                r["expires_on"],
            ])
        story.append(_table(rows, [215, 65, 45, 70]))

    # ── Documents ───────────────────────────────────────────────────────────────

    story.append(Paragraph("Documents", s["h2"]))
    if not documents:
        story.append(Paragraph("No documents saved to the locker.", s["empty"]))
    else:
        rows = [["Document", "Number", "Expires", "Status"]]
        bad_rows = []
        for i, d in enumerate(documents, start=1):
            status = d["expiry"]["status"]
            if status in ("expired", "expiring"):
                bad_rows.append(i)
            rows.append([
                Paragraph(d["label"] or d["doc_label"], s["body"]),
                d["document_no"] or "—",
                d["expiry_date"] or "—",
                status.replace("_", " ").title(),
            ])
        story.append(_table(rows, [175, 90, 65, 65], highlight_rows=bad_rows))

    # ── Recent detections ───────────────────────────────────────────────────────
    story.append(Paragraph("Recent AI sign detections", s["h2"]))
    if not detections:
        story.append(Paragraph("No detections recorded yet.", s["empty"]))
    else:
        rows = [["Sign", "Confidence", "Source", "When"]]
        for p in detections[:15]:
            rows.append([
                Paragraph(p.get("sign_name") or "—", s["body"]),
                f"{(p.get('confidence') or 0) * 100:.1f}%",
                p.get("source_type") or "—",
                (p.get("created_at") or "—")[:16].replace("T", " "),
            ])
        story.append(_table(rows, [175, 70, 60, 90]))

    # ── Footer note ─────────────────────────────────────────────────────────────
    story.append(Spacer(1, 18))
    story.append(Paragraph(
        "This report is assembled from records you entered and from AI predictions made by "
        "this system. Fine deadlines are calculated from the dates you supplied — always "
        "check the charge sheet itself. AI detections may be wrong. Nothing here has legal "
        "standing or substitutes for official records held by the Police or the DMT.",
        s["muted"],
    ))

    doc.build(story)
    return buffer.getvalue()


def report_filename(driver_name: str | None = None) -> str:
    stamp = datetime.now().strftime("%Y%m%d")
    who = (driver_name or "driver").strip().lower().replace(" ", "-")[:40] or "driver"
    return f"roadsafety-report-{who}-{stamp}.pdf"
